spring:
  application:
    name: lm-comments
  datasource:
    url: jdbc:postgresql://localhost:5432/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: '8084'
file:
  upload-dir: C:/Users/Diego/Desktop/app-uploads
app:
  upload-access-url: http://localhost:8084/uploads/
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: ${JWT_SECRET}
auth:
  service:
    url: http://localhost:8081/api/oauth
issues:
  service:
    url: http://localhost:8080/api/issues
